### PR TITLE
add_mari

### PR DESCRIPTION
**Pull request by loonghao**
Add mari to scriptsmenu

### CODE REVIEW

**Comment by loonghao** [comment]
Hi, Just a simple update to support mari.
image

**Comment by BigRoy** [comment]
Nice - I don't use Mari so I can't test, but if this is stable then I guess it's ready to merge.

**Comment by BigRoy** [comment]
@loonghao is this stable in the current version?

**Comment by loonghao** [comment]
@BigRoy Yes, please.

**Pull request merged**
